### ISSUE TITLE
Sample 05428_O_2 has 3 passed pairs of fastqs on 2 runs

### ISSUE THREAD

**Issue by dmcmanam** [mskcc/LimsRest#102]
Sample 05428_O_2 from 2015 has 3 passed pairs of fastqs on 2 runs but the endpoint only returns 2 fastqs instead of 6.

**Comment by anoronh4** [comment]
i also found an issue with 05428_O_20 (same request). a previously curated list has 3 fastq pairs but in our recent lims query we are only finding 1 fastq pair.

**Comment by dmcmanam** [comment]
This was one of the first runs JAX_004 for the JAX sequencer and the flow cell lane information is not present in LIMS so the JAX fastqs are not found.
