### ISSUE TITLE
Some WES samples from request 06938_J are not returning R2 or R1 fastqs

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/LimsRest#113]
When querying the IGOLIMS endpoint, some fastqs are not showing up in the endpoints. The best example is 06938_J, which have run dates as recently as May 2017.

There will be an R1 and an R2, but at times the expected paired fastq (sharing the same `L00x` lane) will be missing, which leads me to believe they are fastqs for different pairing. 

Looking at the fastq directory also shows fastqs that are not showing up in the end points.

Some examples:

06938_J_86
06938_J_80
06938_J_66
06938_J_96
06938_J_7

**Comment by dmcmanam** [comment]
06938_J had multiple re-demuxes and has fastqs by lane after Jan. 2016 for which there was no test case previously.
