### ISSUE TITLE
Some samples return Internal Server Error after endpoints query

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/LimsRest#116]
For example:

```
06048_P_15
06048_P_16
06194_F_2
```

There are others and I can get a more comprehensive list if needed.

**Comment by dmcmanam** [comment]
In the LIMS these samples have parent samples that unexpectedly do not have the normal 12345_1 sample, they instead start from 12345_1_1 for example and may have no 12345_1 aliquot.

**Comment by dmcmanam** [comment]
Or some samples like 06194_E_1 list a LIMS source sample ID that does not exist in LIMS.
