### ISSUE TITLE
07951_L_1 possibly missing fq pair in lims

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#131]
We can see that the sample 07951_L_1 seems to have been sequenced on `PITT_0193_BHT2YMBBXX` and `JAX_0150_BHT523BBXX`. however lims only returns 1 fq pair. can the source of the incongruency be clarified here? we noticed https://github.com/mskcc/LimsRest/issues/118 refers to the same IGO id, but we don't know if there's a relationship.

**Comment by dmcmanam** [comment]
@anoronh4 You are correct, there should be fastqs returned for both PITT & JAX for this sample, I will review further and close this issue when it is fixed.

**Comment by anoronh4** [comment]
excellent! looking forward to it.

**Comment by dmcmanam** [comment]
The LIMS was missing a flowcell relationship for 07951_L_1  related to the JAX run, that is now fixed.
