### ISSUE TITLE
08039_BZ_8 tissueLocation field contains value with newline character

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/LimsRest#137]
For `08039_BZ_8`, one of the fields contain a string value that has a newline character in it.

```
"tissueLocation": "Lung/Middle\n  Lobe",
```

This is breaking some of our downstream processes. I don't think that's a valid entry and IGO might be interested in correcting this, although we will correct it on our end so we're not blocked.

**Comment by allanbolipata** [comment]
Also seen with `08039_BZ_11`:

```
"tissueLocation": "left\n  retroperitoneum",
```

**Comment by timosong** [comment]
`09459_I` has issues with samples containing new line characters in `tissueLocation`

**Comment by dmcmanam** [comment]
I removed the spaces for samples noted above.

**Comment by allanbolipata** [comment]
@dmcmanam Thanks! Will re-import on our end.
