### ISSUE TITLE
Refactor CMO Sample ID generation to ensure all Normal Samples have "N"

### ISSUE THREAD

**Issue by CbourqueMSK** [mskcc/LimsRest#162]
Current code assigns "G" to normal samples with sample origin = organoid. Due to implementation order of operations sample origin is checked first for letter assignment in CMO Sample ID generation code. Sample Class = NORMAL should either be checked first or overwrite any other letter in the implementation to ensure that all samples with Sample Class = NORMAL to have "-NXX" where X is an integer. Current samples identified in 07323_P

**Comment by dmcmanam** [comment]
Meta DB team is taking over CMO Sample ID Generation
