### ISSUE TITLE
05257_CL_3 fastqs found in endpoint do not exist

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/LimsRest#164]
Voyager imported files for [this sample ](https://igolims.mskcc.org:8443/LimsRest/api/getSampleManifest?igoSampleId=05257_CL_3)but we could not find them in the path provided.

**Comment by dmcmanam** [comment]
Currently reviewing whether that fastq should be in the archive or not.

**Comment by dmcmanam** [comment]
The paths for the fastqs for this sample are now correct in the archive and database.
