### ISSUE TITLE
07833_B_1 missing cmoPatientId, cmoSampleName in most recent endpoint query

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/LimsRest#166]
In May 2020, the data for `07833_B_1` had cmoPatientId and cmoSampleName; that data now is missing.

Were these removed?

**Comment by dmcmanam** [comment]
We removed a bunch of old duplicate records in the samplecmoinforecords table and this link was lost.  I put the references back for 07833_B.

**Comment by allanbolipata** [comment]
@dmcmanam Thanks for checking this. Do you know if this was an isolated issue or if it happened for other samples/requests?
