### ISSUE TITLE
07250_BN is missing fastqs

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#172]
request 07250_BN has 6 samples that are "IGO complete" but there is no fastq path presented in swagger. can we correct the issue, and also put in place some sort of check to catch these issues? being igo complete and not having fastqs (at least for sequencing projects) seems like an issue that should be flagged immediately.

**Comment by dmcmanam** [comment]
This issue is fixed.  The data team is moving every fastq to a new storage location and changing our delivery process so we need to work on that for the next two sprints then we can add the check.
