### ISSUE TITLE
10570_C is igoComplete=True but no fastq paths

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#200]
All samples for 10570_C are marked as igocomplete=True but none of the samples have fastqs according to Swagger. We got an email notification about the completion of this project just yesterday. #172 is a similar issue. It would be helpful if this kind of situation was immediately flagged. in swagger the libraries just look like `"libraries":[]`

Side note, is "Fingernails" a valid preservation type, as it says for `10570_C_8`?

**Comment by anoronh4** [comment]
same problem for request ID 11361

**Comment by dmcmanam** [comment]
I see that this PITT_0517 run had a custom demux which is causing the fastq paths to not get returned in the endpoint.  I'm working on fixing this.

**Comment by dmcmanam** [comment]
These two projects are now correctly displaying in the endpoint.
