### ISSUE TITLE
feature request: search lims by fastq

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#227]
it sometimes happens to us where we have a fastq pair and an outdated cmo id associated with it that is likely renamed to something else, but we can't do a search for the fastq in the lims. searching by the igo/request id that is in the fastq path may not turn up the fastq we are looking for, but we don't know if the fastq simply went to another sample/request, if it was dropped out of the lims for other reasons. it might be a helpful feature if we are able to search by fastq path without having to know metadata.

for example the filepath `/igo/delivery/FASTQ/PITT_0028_AH3W5NBBXX/Project_06208/Sample_BRCA-01136-T_IGO_06208_10/BRCA-01136-T_IGO_06208_10_S24_L008_R1_001.fastq.gz`, and seems to be related to a past listed in our old megatron mapping file. however, it doesn’t show up in the lims when i search for 06208_10  or anything else in the same request, and i have no direct way of knowing how it dropped out.

**Comment by dmcmanam** [comment]
For 06208 I updated the LIMS so that the PITT fastqs will be returned.
