### ISSUE TITLE
fastqs missing from `/igo/delivery`

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#228]
some fastq pairs that existed in `/ifs/archive` were found to not have been moved over to `/igo/delivery` (or at least, i do not have permission to access them). All belong to the request 05513, and to flowcells `MOMO_0060_BC6BVJANXX` and `MOMO_0062_BC62ECANXX`. for example, the previous path `/ifs/archive/GCL/hiseq/FASTQ/MOMO_0060_BC6BVJANXX/Project_5513/Sample_TS04-T/TS04-T_GTGGCC_L004_R1_001.fastq.gz` is not accessible to me at `/igo/delivery/FASTQ/MOMO_0060_BC6BVJANXX/Project_5513/Sample_TS04-T/TS04-T_GTGGCC_L004_R1_001.fastq.gz`.

if they do not get copied to `/igo/delivery` soon they may be lost when we decommission `/ifs/archive`, and we need time after they are copied there, so that we may save backups into the permanent cmo space.

**Comment by dmcmanam** [comment]
That is an old project with fastqs from 2015.  They are now readable by the group 'cmoigo'.
