### ISSUE TITLE
internal server error for getSampleManifest

### ISSUE THREAD

**Issue by anoronh4** [mskcc/LimsRest#245]
for certain samples i am getting:
```
$ curl -u bicreader:floatmonsterpoem -k -X GET "https://igolims.mskcc.org:8443/LimsRest/api/getSampleManifest?igoSampleId=93017_S_5" -H "accept: */*"
{"timestamp":"2021-04-15T19:10:12.931+0000","status":500,"error":"Internal Server Error","message":"500 INTERNAL_SERVER_ERROR","path":"/LimsRest/api/getSampleManifest"}
```
if i change the sample to 93017_S_70, for example, metadata returns with no error. I can see through `getRequestSamples` that `93017_S_5` exists so there is no reason for it to not return.

**Comment by dmcmanam** [comment]
There is no CMO record in our database for that sample.  This will now return the paths to the fastq.gz files.
