### ISSUE TITLE
External specimen not recognized when creating sample set

### ISSUE THREAD

**Issue by imprezka88** [mskcc/LimsRest#68]
When sample set is created with external specimen and pairing with external specimen there is an error:
Record Id:FAILURE: FAILURE: Please confirm that P-0038250-N01-IM6 and 06048_AQ_2 are known samples. TRACE:java.lang.RuntimeException: FAILURE: Please confirm that P-0038250-N01-IM6 and 06048_AQ_2 are known samples. at org.mskcc.limsrest.limsapi.AddOrCreateSet.validateIfPairingSamplesBelongToSet(AddOrCreateSet.java:207) at org.mskcc.limsrest.limsapi.AddOrCreateSet.addPairings(AddOrCreateSet.java:194) at org.mskcc.limsrest.limsapi.AddOrCreateSet.execute(AddOrCreateSet.java:130) at com.velox.sapioutils.client.standalone.VeloxStandalone.run(VeloxStandalone.java:60) at org.mskcc.limsrest.limsapi.LimsTask.call(LimsTask.java:62) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

Reason: Pairing is validated before external specimen ids are added to sample set's samples

**Comment by ckandoth** [comment]
Make sure that @dmcmanam and I are reviewers on your PR. This code is still shared between CMO and IGO and critical for production ops. Thanks.

**Comment by ckandoth** [comment]
@imprezka88 go ahead and implement this in a new bugfix branch. But let @dmcmanam decide what branch this should get merged into. We'll figure it out next week.

**Comment by imprezka88** [comment]
@ckandoth  @dmcmanam I cannot commit to this repo. I'm getting:
remote: Permission to mskcc/PiExemplarRest.git denied to imprezka88.
fatal: unable to access 'https://github.com/mskcc/PiExemplarRest.git/': The requested URL returned error: 403

**Comment by ckandoth** [comment]
@imprezka88 I have given you write access, but not to the master branch. The master branch is now protected from non-admins, and requires a pull-request with at least 1 reviewer before merging. @dmcmanam you can see these settings here - https://github.com/mskcc/PiExemplarRest/settings/branches
