### ISSUE TITLE
CMOSampleClass "Tumor" is an old alias for "Unknown Tumor"

### ISSUE THREAD

**Issue by ckandoth** [mskcc/LimsRest#69]
The `CMOSampleClass` field in `SampleCMOInfoRecords` no longer has `Tumor` as a valid value, however a lot of older records still say "Tumor". At some point, this was renamed to `Unknown Tumor` which all newer records use. When assigning CMO sample IDs, this causes an issue with how the sample counter is incremented. Please add `Tumor` as something that resolves to `T` in [ClassSampleAbbreviationResolver.java](https://github.com/mskcc/PiExemplarRest/blob/master/src/main/java/org/mskcc/limsrest/limsapi/cmoinfo/cspace/ClassSampleAbbreviationResolver.java)

**Comment by imprezka88** [comment]
if we change it that way also new samples which will get incorrectly assigned "Tumor" will be treated as correct ones. Is it fine?

**Comment by imprezka88** [comment]
@ckandoth @dmcmanam I cannot commit to this repo. I'm getting:
remote: Permission to mskcc/PiExemplarRest.git denied to imprezka88.
fatal: unable to access 'https://github.com/mskcc/PiExemplarRest.git/': The requested URL returned error: 403

I committed changes only to common-domain for now
